---
- name: Deploy web App
  hosts: n2
  become: yes

  tasks:
    - name: install Git
      ansible.builtin.yum:
        name: git
        state: present

    - name: Host Code
      ansible.builtin.git:
        repo: https://github.com/CeeyIT-Solutions/ecomm-3
        dest: /var/www/html
...